---
# tasks file for k8s_master
 - name: Installing docker services in master
   package:
       name: docker
       state: present
 - name: Starting docker services  
   service:
       name: docker
       state: started
       enabled: yes
 - name: Setting yum repo to install k8s in master node
   yum_repository:
        name: Kubernetes
        description: kubernetes Repo
        file: kubernetes
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
        gpgcheck: 1
        enabled: 1
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        repo_gpgcheck: 1
   changed_when: false  
 - name: Installing Kubernetes access softwares
   package:
        name: "{{ item }}"
        state: present
   loop:
        - kubeadm
        - iproute-tc
        - kubectl
 - name: Enabling kubelet service
   service:
       name: kubelet
       state: started
       enabled: yes
 - name: Pulling important docker images for Kubernetes Cluster
   command: kubeadm config images pull
 - name: Changing docker driver for kubernetes support
   copy:
       dest: /etc/docker/daemon.json
       content: |
          {
             "exec-opts": ["native.cgroupdriver=systemd"]
          }
 - name: Restarting Docker services
   service:
       name: docker
       state: restarted
 - name: Setting up IP Table
   copy:
      dest: /etc/sysctl.d/k8s.conf
      content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
 - name: Restarting sysctl to update IP Configuration
   command: sysctl --system
 - name: Starting Kubernetes Cluster
   shell: "kubeadm init --pod-network-cidr=10.240.0.0/16  --ignore-preflight-errors=NumCPU  --ignore-preflight-errors=Mem"
   ignore_errors: yes
 - name: creating directory for kubernetes config
   file:
      path: $HOME/.kube
      state: directory
 - name: Copying the default file in this home directory
   command: "cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"
 - name: Changing Ownership to Kubectl client
   shell: "chown $(id -u):$(id -g) $HOME/.kube/config"
 - name: Configuring flannel CNI for k8s master
   shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
 - name: Droping caches from RAM
   command: "echo 3 > /proc/sys/vm/drop_caches"
 - name: Generating token for connecting to worker node
   command: "kubeadm token create --print-join-command"
   register: tokens
   ignore_errors: yes
 - debug:
       var: tokens.stdout_lines
